name: Scheduled Curl Script

on:
  schedule:
    - cron: '* * * * *' # Menjalankan setiap 1 menit

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Run Curl Script
        run: curl -X POST -d "q=livexords@114.4.218.148" https://pastelfaucet.com/send.php
